spring:
  application:
    name: kiwi

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC



  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
        max-file-size: 10MB
        max-request-size: 10MB

  web:
    resources:
      static-locations: file:///C:/uploads/



#  mail:
#    host: smtp.gmail.com
#    username: ${EMAIL}
#    port: 587
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#          auth: true
#    password: ${EMAIL_CODE}

jwt:
  secret: ${JWT_SECRET}
  access: 2592000000
  refresh: 2592000000

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true